default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: <%= ENV['RECIPES_APP'] %>
  # password: <%= ENV['RECIPES_APP'] %>
  # host: <%= ENV['PG_HOST'] || 'localhost' %>

development:
  <<: *default
  database: recipes_app_development

test:
  <<: *default
  database: recipes_app_test

production:
  <<: *default
  database: recipes_app_production
  username: recipes_app
  password: <%= ENV['RECIPES_APP_DATABASE_PASSWORD'] %>